steps:
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/znt-template-nest-bke:$BUILD_ID', '.']

  - id: 'Push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/znt-template-nest-bke:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'znt-template-nest-bke-run'
      - '--image'
      - 'gcr.io/$PROJECT_ID/znt-template-nest-bke:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--env-vars-file=env.yaml'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--service-account'
      - 'znt-development-app-dev001@appspot.gserviceaccount.com'
