module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.module.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.ports.ts',
    '!src/main.ts',
    '!src/**/index.ts',
    '!src/**/migrations/**',
    '!src/**/entities/**',
    '!src/**/adapters/**',
    '!src/**/models/**',
    '!src/**/exceptions/**',
    '!src/**/constants/**',
    '!src/**/logger/**',
    '!src/**/config/**',
    '!src/**/test/**',
  ],
  coverageDirectory: './coverage',
  coverageProvider: 'v8',
  coverageReporters: ['text', 'lcov'],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
};
