steps:
  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_DOCKER_REPOSITORY}/client-system-backend:$BUILD_ID',
        '.',
      ]

  - id: 'Push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_DOCKER_REPOSITORY}/client-system-backend:$BUILD_ID',
      ]
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'client-system-backend-${_ENV}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_DOCKER_REPOSITORY}/client-system-backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--service-account'
      - '${_RUN_SERVICE_ACCOUNT_EMAIL}'
      - '--set-env-vars=ENV=${_ENV}'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars=LIST_CORS=${_LIST_CORS}'
      - '--set-env-vars=TOKEN_EXPIRATION=${_TOKEN_EXPIRATION}'
      - '--set-env-vars=SECRETKEY_AUTH=${_SECRETKEY_AUTH}'
      - '--set-env-vars=EXTERNAL_API__SECURITY_TYPE=${_EXTERNAL_API_SECURITY_TYPE}'
      - '--set-env-vars=EXTERNAL_API_TOKEN=${_EXTERNAL_API_TOKEN}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'

options:
  logging: CLOUD_LOGGING_ONLY